# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
<<<<<<< HEAD
  secret_key_base: e32b5a8c13a2b3ed86b3d642aae7a2ae2b2ca30be5260125fa5a507a6cab46852140d5694b153115b2069c6ba45058b1ee4ba138062c95bffed9748bea61ce6d

test:
  secret_key_base: 76ea89d2777b788d2b28a42feca336f44102387556a968e9c85aa504f666f7e27acdecb4e3793f644c0476bf0f26f2e0020fe6fd951b6e822b743c9c40d0dfe9
=======
  secret_key_base: 792c49995b8e4998af776cb801f8a7c2bf893af1a6ba50a8d30e9d8dffbb1ead63138be48b3492e2c0cb4be2ca52650daad231a6658c1ce8ce3f8d1ac0c1439a

test:
  secret_key_base: b07c7842bb27335acd2372ef45b5cf3fbfe0125b486a3e0ee9411aad148aaa37f1e533ff2bacc5bfaadd6279858ed8565686e7afc8b1acc0d4c29a15d6980fd1
>>>>>>> bd2e8496480584370d72914f80b6da766f4216ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
